name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          version: 1.0.2

      - name: Install dependencies
        run: bun install

      - name: Handle version release (PR or npm publish)
        uses: changesets/action@v1
        with:
          title: Release new version
          commit: ci: release new version
          publish: bun run build && bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
